---
live_environments:
  vars:
    ansible_connection: ssh
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  hosts:
    arch-desktop-iso.local:
      ansible_user: root
    arch-macbook-iso.local:
      ansible_user: root
    arch-laptop-iso.local:
      ansible_user: root
    ubuntu-desktop-iso.local:
      ansible_user: ubuntu
    ubuntu-macbook-iso.local:
      ansible_user: ubuntu
    ubuntu-laptop-iso.local:
      ansible_user: ubuntu
    rpi5-iso.local:
      ansible_user: pi
