---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-errors: true
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-archlinux}
    dockerfile: Dockerfile.${MOLECULE_DISTRO:-archlinux}.j2
    platform: "${MOLECULE_PLATFORM:-linux/amd64}"
    pre_build_image: false
    privileged: true
    command: "${MOLECULE_COMMAND:-/lib/systemd/systemd}"
    tmpfs:
      - "/tmp"
      - "/run"
      - "/opt"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "/dev:/dev:rw"
    cgroupns_mode: host
provisioner:
  name: ansible
  inventory:
    links:
      host_vars: "../../host_vars/"
  env:
    MOLECULE_DISTRO: "${MOLECULE_DISTRO:-archlinux}"
    ANSIBLE_ROLES_PATH: "../../roles"
  config_options:
    defaults:
      fact_caching: jsonfile
      fact_caching_connection: /tmp/facts_cache
      fact_caching_timeout: 600
      callback_result_format: yaml
      interpreter_python: /usr/bin/python3
    ssh_connection:
      pipelining: true
  playbooks:
    converge: converge.yml
verifier:
  name: ansible

# disable idempotency test for this playbook as it is not idempotent in nature
scenario:
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
