---
- name: Prepare
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Create virtual disk image"
      become: true
      community.general.filesize:
        path: "/opt/vdd.img"
        size: 12G
        mode: "0755"

    - name: "Create test_device (loop block device)"
      become: true
      ansible.builtin.command:
        cmd: "losetup --show -Pf /opt/vdd.img"
      register: loop_device
      changed_when: true

    - name: "Show test device"
      ansible.builtin.debug:
        msg: "Test device: {{ loop_device.stdout }}"
